### ISSUE TITLE
AI does not ahere to Pop Cap

### ISSUE THREAD

**Issue by Larrythree** [gruenwaldlk/eaw-layerz#1]
Greetings, gruenwaldlk. I am the dev to the Alliance at War mod. I recently integrated your layer Z script into my mod and it was working, but there was a side effect. The AI would ignore the Population Capacity limit and could spawn all the ships it had in its fleet. I ran multiple test to confirm it was your script. I felt sad knowing it was as I REALLY was excited to use it. If you can fix this issue, I would be grateful. I ran into other modders experiencing this issue; all of them excited to use your layer z script. We would all be happy if you could fix this issue.

-- Larry-3

**Comment by gruenwaldlk** [comment]
I'm currently investigating the issue, but as I mentioned in the Discord chat, it might be down to a workaround for a bug that prevents the unit from not being assigned to the AI freestore correctly.

If that is the case I'll have to look into alternatives that may come with visual glitches, but I'd rather have those than the AI being broken in one way or another.

Fun fact: It is an AI only issue, I can't seem to break it for the player, which indicates that popcap is calculated differently or at a different time for human vs. AI, which is weird.

**Comment by Larrythree** [comment]
Thank you for the fun fact, and for trying to fix this. I really want to use your script. I and others will be rooting for you, and waiting to see what becomes of this.

**Comment by gruenwaldlk** [comment]
I've published a relese candidate that should fix the issue. When testing make sure to keep an eye on whether AI units get randomly left behind, which may indicate that they are not being assigned to the FreeStore properly.

https://github.com/gruenwaldlk/eaw-layerz/releases/tag/release_candidates%2Fv1.0.1-rc.00
